config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  namespace :admin do
    root "dashboard#index"
    get "dashboard" => "dashboard#index", :as => :dashboard

    devise_scope :user do
      get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
      get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
    end

    devise_for :users, controllers: { sessions: 'admin/users/sessions'}, :passwords => 'admin/users/passwords', :skip => [:registrations]

    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
      patch 'users' => 'devise/registrations#update', :as => 'update_user_registration'
    end

    resources :products
    resources :quicks
    resources :types
    resources :brands
    resources :banners
    resources :slideshows
    resources :bigbanners
    resources :users
    resources :abouts
    resources :blogs
    resources :settings
    resources :items
    resources :categories
    resources :sparpartbrands
    resources :modes
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homes#index"
  resources :homes
  resources :products, only: [:index, :show]
  resources :brands, only: [:index, :show]
  resources :types, only: [:index, :show]
  resources :contacts, only: [:new, :create]
  resources :aboutus, only: [:index]
  resources :blogs, only: [:index, :show]
  resources :sparparts, only: [:index, :show]
  resources :items, only: [:index, :show]
  resources :sparpartbrands, only: [:index, :show]
  resources :modes, only: [:index, :show]
end

app/models/mode.rb
class Mode < ApplicationRecord
  before_save :update_slug

  has_many :items, dependent: :destroy
  belongs_to :user


  def update_slug
    self.slug = mode_name.parameterize
  end

  def to_param
    slug
  end

  validates :mode_name, presence: true
  validates :mode_name, uniqueness: {case_sensitive: false}
end

app/controllers/admin/modes_controller.rb
class Admin::ModesController < ApplicationController
  before_action :authenticate_admin_user!
  before_action :admin_only?

  def index
    if Sparpartbrand.exists?
      @mode = current_admin_user.modes.build
    else
      redirect_to admin_sparpartbrands_path
      flash[:error] = "Please input brand first before you get start with your product"
    end
    @modes = Mode.all
  end

  def show
    @mode = Mode.find_by_slug(params[:id])
  end

  def new

  end

  def create
    @mode = current_admin_user.modes.build(mode_params)
    if @mode.save
      respond_to do |format|
        flash.now[:notice] = "Successful Created"
        format.html { redirect_to admin_modes_path }
        format.js
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please fill the field blank or mode Duplicated"
        format.html { redirect_to admin_modes_path }
        format.js { render template: "admin/modes/mode_error.js.erb" }
      end
    end
  end

  def edit
    @mode = Mode.find_by_slug(params[:id])
  end

  def update
    @mode = Mode.find_by_slug(params[:id])
    if @mode.update(mode_params)
      redirect_to admin_mode_path(@mode), notice: "Successful Updated"
    else
      render :edit
    end
  end

  def destroy
    @mode = Mode.destroy(params[:id])
    respond_to do |format|
      flash.now[:error] = "Delete"
      format.html { redirect_to admin_modes_url }
      format.js
    end
  end

  private
    def admin_only?
      unless  current_admin_user.admin?
        unless @user == current_admin_user
          redirect_to admin_dashboard_path, notice: "Access Denied"
        end
      end
    end

    def mode_params
      params.required(:mode).permit!
    end
end

app/controllers/modes_controller.rb
class ModesController < FrontEndApplicationController
  def index
    @items = Item.all.page params[:page]
    @categories = Category.all
  end

  def show
    @mode = Mode.find_by_slug(params[:id])
    @items = @mode.items.page params[:page]
    @categories = Category.all
  end
end

app/views/modes/index.html.erb
<% title "Products | tgshobbycambodia.com"%>
<div class="wrap-main wrap-main-02">
  <%=render "components/front/header"%>
  <div class="site-content-contain">
    <div id="content" class="site-content">
        <div class="wrap container">
            <div class="row">
                <div class="col-md-9 col-md-push-3">
                    <div id="primary" class="content-area">
                        <nav class="woocommerce-breadcrumb" style="margin-top: 30px; margin-bottom: 30px;">
                            <a href="/">Home</a>
                              <%=link_to "Model", modes_path, class: "active"%>
                        </nav>

                        <ul class="row products">
                          <%@items.each do |item|%>
                              <% if item.status%>
                                <li class="col-md-4 col-sm-6 col-xs-6 grid-item">
                                  <div class="product type-product has-post-thumbnail">
                                    <div class="product-image">
                                      <%=link_to item_path(item) do%>
                                      <img src="<%=item.image%>" alt="shop item">
                                      <%end%>

                                      <div class="product-action">
                                        <%=link_to item_path(item) do%>
                                        <i class="fa fa-heart-o"></i>
                                        <%end%>
                                        <%=link_to item_path(item) do%>
                                        <i class="fa fa-search-plus"></i>
                                        <%end%>
                                        <%=link_to item_path(item) do%>
                                        <i class="fa fa-list-ul"></i>
                                        <%end%>
                                      </div>
                                    </div>
                                    <h3>
                                      <%=link_to item.item_name, item_path(item)%>
                                    </h3>
                                      <p style="font-size:17px;">Model: <%=link_to item.mode.mode_name, item.mode, style: "color: #575757;font-size: 19px; font-weight:bold;"%></p>
                                    <div class="price">
                                      <span class="woocommerce-Price-amount amount"><%=number_to_currency(item.price)%></span>
                                    </div>
                                    <div class="product-info">
                                      <div class="star-rating">
                                        <span>
                                          <strong class="rating">4</strong>
                                          out of 5,
                                        </span>
                                      </div>
                                      <%=link_to "Show Detail", item_path(item), class: "button add_to_cart_button"%>
                                    </div>
                                  </div>
                                </li>
                            <%end%>
                          <%end%>
                        </ul>

                        <%= paginate @products %>
                    </div>
                </div>
                <div class="col-md-3 col-md-pull-9">
                    <div id="secondary" class="sidebar-shop">

                        <section class="widget woocommerce widget_list_categories_product">
                            <!--widget_product_categories-->
                            <h2 class="widget-title">Parts & Accessories</h2>
                            <ul class="product-categories">
                              <%@categories.each do |cate|%>
                                <li id="<%=cate.category_name.upcase.delete(' ')%>" >
                                  <a data-toggle="collapse" href="#<%=cate.category_name.downcase.delete(' ')%>-<%=cate.id%>" class="medusae-collapse collapsed" aria-expanded="false" aria-controls="laptop">
                                    <i class="fa fa-laptop"></i>
                                    <%=cate.category_name.upcase%>
                                  </a>
                                  <ul id="<%=cate.category_name.downcase.delete(' ')%>-<%=cate.id%>" class="collapse" aria-expanded="false">
                                    <%cate.sparpartbrands.distinct.each do |sparpartbrand|%>
                                      <li>
                                        <%=link_to sparpartbrand_path(sparpartbrand) do%>
                                          <i class="fa fa-laptop"></i>
                                          <%=sparpartbrand.brand_name.upcase%>
                                        <%end%>
                                      </li>
                                    <%end%>
                                  </ul>
                                </li>
                              <%end%>
                            </ul>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>
 </div>
</div>
<%=render "components/front/footer"%>

app/views/modes/show.html.erb
<% title "Products | tgshobbycambodia.com"%>
<div class="wrap-main wrap-main-02">
  <%=render "components/front/header"%>
  <div class="site-content-contain">
    <div id="content" class="site-content">
        <div class="wrap container">
            <div class="row">
                <div class="col-md-9 col-md-push-3">
                    <div id="primary" class="content-area">
                        <nav class="woocommerce-breadcrumb" style="margin-top: 30px; margin-bottom: 30px;">
                            <a href="/">Home</a>
                            <%=link_to "Model", modes_path%>
                            <%=link_to @mode.mode_name,'#', class: "active"%>
                        </nav>

                        <ul class="row products">
                            <%@items.each do |item|%>
                                <% if item.status%>
                                  <li class="col-md-4 col-sm-6 col-xs-6 grid-item">
                                    <div class="product type-product has-post-thumbnail">
                                      <div class="product-image">
                                        <%=link_to item_path(item) do%>
                                        <img src="<%=item.image%>" alt="shop item">
                                        <%end%>

                                        <div class="product-action">
                                          <%=link_to item_path(item) do%>
                                          <i class="fa fa-heart-o"></i>
                                          <%end%>
                                          <%=link_to item_path(item) do%>
                                          <i class="fa fa-search-plus"></i>
                                          <%end%>
                                          <%=link_to item_path(item) do%>
                                          <i class="fa fa-list-ul"></i>
                                          <%end%>
                                        </div>
                                      </div>
                                      <h3>
                                        <%=link_to item.item_name, item_path(item)%>
                                      </h3>
                                      <p style="font-size:17px;">Model: <%=link_to item.mode.mode_name, item.mode, style: "color: #575757;font-size: 19px; font-weight:bold;"%></p>
                                      <div class="price">
                                        <span class="woocommerce-Price-amount amount"><%=number_to_currency(item.price)%></span>
                                      </div>
                                      <div class="product-info">
                                        <div class="star-rating">
                                          <span>
                                            <strong class="rating">4</strong>
                                            out of 5,
                                          </span>
                                        </div>
                                        <%=link_to "Show Detail", item_path(item), class: "button add_to_cart_button"%>
                                      </div>
                                    </div>
                                  </li>
                              <%end%>
                            <%end%>
                        </ul>

                        <%= paginate @items %>
                    </div>
                </div>
                <div class="col-md-3 col-md-pull-9">
                    <div id="secondary" class="sidebar-shop">

                        <section class="widget woocommerce widget_list_categories_product">
                            <!--widget_product_categories-->
                            <h2 class="widget-title">Parts & Accessories</h2>
                            <ul class="product-categories">
                              <%@categories.each do |cate|%>
                                <li id="<%=cate.category_name.upcase.delete(' ')%>" >
                                  <a data-toggle="collapse" href="#<%=cate.category_name.downcase.delete(' ')%>-<%=cate.id%>" class="medusae-collapse collapsed" aria-expanded="false" aria-controls="laptop">
                                    <i class="fa fa-laptop"></i>
                                    <%=cate.category_name.upcase%>
                                  </a>
                                  <ul id="<%=cate.category_name.downcase.delete(' ')%>-<%=cate.id%>" class="collapse" aria-expanded="false">
                                    <%cate.sparpartbrands.distinct.each do |sparpartbrand|%>
                                      <li>
                                        <%=link_to sparpartbrand_path(sparpartbrand) do%>
                                          <i class="fa fa-laptop"></i>
                                          <%=sparpartbrand.brand_name.upcase%>
                                        <%end%>
                                      </li>
                                    <%end%>
                                  </ul>
                                </li>
                              <%end%>
                            </ul>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>
 </div>
</div>
<%=render "components/front/footer"%>