config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  namespace :admin do
    root "dashboard#index"
    get "dashboard" => "dashboard#index", :as => :dashboard

    devise_scope :user do
      get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
      get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
    end

    devise_for :users, controllers: { sessions: 'admin/users/sessions'}, :passwords => 'admin/users/passwords', :skip => [:registrations]

    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
      patch 'users' => 'devise/registrations#update', :as => 'update_user_registration'
    end

    resources :products
    resources :quicks
    resources :types
    resources :brands
    resources :banners
    resources :slideshows
    resources :bigbanners
    resources :users
    resources :abouts
    resources :blogs
    resources :settings
    resources :items
    resources :categories
    resources :sparpartbrands
    resources :modes
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homes#index"
  resources :homes
  resources :products, only: [:index, :show]
  resources :brands, only: [:index, :show]
  resources :types, only: [:index, :show]
  resources :contacts, only: [:new, :create]
  resources :aboutus, only: [:index]
  resources :blogs, only: [:index, :show]
  resources :sparparts, only: [:index, :show]
  resources :items, only: [:index, :show]
  resources :sparpartbrands, only: [:index, :show]
  resources :modes, only: [:index, :show]
end

app/models/setting.rb
class Setting < ApplicationRecord
  belongs_to :user
  has_many :socials, inverse_of: :setting
  accepts_nested_attributes_for :socials, :reject_if => :all_blank, :allow_destroy => true

  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < ApplicationController
  before_action :authenticate_admin_user!
  before_action :admin_only?

  # before_action :set_setting, only: [:destroy]
  def index
    @setting = current_admin_user.settings.build
    @settings = Setting.all
  end

  def show
    @setting = Setting.find_by(params[:id])
  end

  def new

  end

  def create
    @setting = current_admin_user.settings.build(setting_params)
    if @setting.save
      respond_to do |format|
        # flash[:success] = "Successful Created"
        flash.now[:notice] =  " Successful Craeted"
        format.html { redirect_to @setting}
        format.js
      end
    else
      respond_to do |format|
        flash.now[:error] = "Please fill the field blank"
        format.html { redirect_to new_admin_setting_path }
        format.js { render template: 'admin/settings/setting_error.js.erb' }
      end
    end
  end

  def edit
    @setting = Setting.find(params[:id])
    if !@setting.socials.exists?
      1.times do
        @social = @setting.socials.build
      end
    else
      @setting = Setting.find(params[:id])
    end
  end

  def update
    @setting = Setting.find(params[:id])
    if @setting.update(setting_params)
      redirect_to admin_setting_path(@setting)
    else
      render :edit
    end
  end

  def destroy
    @setting = Setting.destroy(params[:id])
    respond_to do |format|
      flash.now[:error] = "Delete"
      format.html { redirect_to admin_settings_url }
      format.js
    end
  end


  private
    def setting_params
      params.required(:setting).permit!
    end

    def admin_only?
      unless current_admin_user.admin?
        unless @user == current_admin_user
          redirect_to admin_dashboard_path, notice: "Access Denied"
        end
      end
    end
end

app/views/admin/settings/_setting.html.erb
<tr class="delete_setting_<%=setting.id%>">
  <td style="width: 50%;">
    <%=image_tag(setting.image,style: "width: 100%;")%>
  </td>

  <td>
    <%=form_for([:admin, setting], remote: true) do |f|%>
      <%=link_to admin_setting_path(setting), title: "View" do %>
        <i class="fa fa-eye btn-view"></i>
      <%end%>
      <%=link_to edit_admin_setting_path(setting), title: "Edit" do %>
        <i class="fa fa-pencil btn-edit"></i>
      <%end%>
      <%=link_to admin_setting_path(setting.id), title: "Delete", method: :delete, data: { confirm: "Are Sure You To Delete ?"}, remote: true do%>
        <i class="fa fa-remove btn-remove"></i>
      <%end%>
    <%end%>
  </td>
</tr>

app/views/admin/settings/_setting_form.html.erb
<div class="row">
    <div class="col-sm-12">
      <h4 class="mt-0 header-title">Logo</h4>
          <%=form_for([:admin, setting], remote: true , html: { id: "form-horizontal", class: "form-horizontal form-wizard-wrapper"})do |f|%>
            <fieldset>
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                      <div class="control-group file-upload" id="file-upload1">
                        <div class="image-box text-center"><p>Upload Image</p><img src="" alt=""></div>
                        <div class="controls">
                          <%=f.file_field :image%>
                        </div>
                      </div>
                  </div>
                </div>
              </div>
            </fieldset>

            <%=f.fields_for :socials do |social|%>
              <%=render "social_fields", :f => social%>
            <%end%>

            <div class="form-group" style="margin-top: 20px;">
              <%=f.submit "Save", class:"btn btn-success"%>
              <%= link_to_add_association "Add social", f, :socials, class: "btn btn-primary"%>
              <%= link_to "Cancel", admin_settings_path, class: "btn btn-danger"%>
            </div>
        <%end%>
    </div>
</div>

app/views/admin/settings/_social_fields.html.erb
<div class="nested-fields">
  <h3>Social</h3>
  <div class="row">
    <div class="col-sm-12">
      <div class="">
        <div class="row">
          <div class="col-md-12">
            <%=link_to_remove_association "Remove", f, class: 'btn btn-danger'%>
          </div>
          <div class="col-sm-12">
            <div class="form-group">
              <div class="">
                <label for="example-text-input" class="">social</label>
                <%= f.select :socialm, Social::SECTION_SELECT_SOCIAL, {}, {:class=>"form-control"} %>
              </div>
            </div>
          </div>

          <div class="col-sm-12">
            <div class="form-group">
              <div class="">
                <label for="example-text-input" class="">URL</label>
                <%=f.text_field :url, class: "form-control"%>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>

</div>

app/views/admin/settings/create.js.erb
$("#setting-success").html("<%= custom_flash_message%>");
$("#setting-index").append("<%= j render(@setting)%>");


  $(function() {
  	$('.delete_setting_<%=@setting.id%>').submitOnCheck();
  });

  $('.delete_setting_<%=@setting.id%>').submitOnCheck();

app/views/admin/settings/destroy.js.erb
$('.delete_setting_<%=@setting.id%>').remove();

app/views/admin/settings/edit.html.erb
<%=render "components/header"%>

  <div class="wrapper">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="page-title-box">
              <div class="btn-group pull-right">
                  <ol class="breadcrumb hide-phone p-0 m-0">
                    <li class="breadcrumb-item"><a href="#">Products</a></li>
                    <li class="breadcrumb-item active">Dashboard</li>
                  </ol>
              </div>
              <h4 class="page-title">Products</h4>
          </div>
        </div>
      </div>
      <div class="row">

      </div>
      <div class="row">
        <div class="col-lg-8">
          <div class="card m-b-20">
            <div class="card-block">
              <div class="product-form">
                <%=simple_form_for([:admin, @setting])do |f|%>
                <div class="container">
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="form-group">
                          <div class="control-group file-upload" id="file-upload1">
                            <div class="image-box text-center"><p>Upload Image</p><img src="" alt=""></div>
                            <div class="controls">
                              <%=f.file_field :image%>
                            </div>
                          </div>
                      </div>
                    </div>

                    <%=f.fields_for :socials do |social|%>
                      <%=render "social_fields", :f => social%>
                    <%end%>

                    <div class="col-sm-12">
                      <div class="form-group" style="margin-top: 20px;">
                        <%=f.submit "Save", class:"btn btn-success"%>
                        <%= link_to_add_association "Add social", f, :socials, class: "btn btn-primary"%>
                        <%= link_to "Cancel", admin_settings_path, class: "btn btn-danger"%>
                      </div>
                    </div>
                  </div>
                  </div>
                <%end%>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>
  </div>

<%=render "components/footer"%>

app/views/admin/settings/index.html.erb
<%=render "components/header"%>

  <div class="wrapper">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="page-title-box">
              <div class="btn-group pull-right">
                  <ol class="breadcrumb hide-phone p-0 m-0">
                    <li class="breadcrumb-item"><a href="#">settings</a></li>
                    <li class="breadcrumb-item active">Dashboard</li>
                  </ol>
              </div>
              <h4 class="page-title">settings</h4>
          </div>
        </div>
      </div>
      <div class="row">

      </div>
      <div class="row">
        <div class="col-lg-8">
          <div class="card m-b-20">
            <div class="card-block">
              <button type="button" class="btn btn-primary waves-effect waves-light" data-toggle="modal" data-target=".bs-example-modal-lg">Add New</button>
              <br><br>
              <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title mt-0" id="myLargeModalLabel">New setting</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                      </div>
                      <div class="modal-body">
                        <div class="col-12">
                          <div class="">
                            <div class="" id="settings">
                              <div id="setting-errors"></div>
                              <div id="setting-success"></div>
                              <%= render partial: "setting_form", locals: {setting: @setting}%>
                            </div>
                          </div>
                        </div>
                      </div>
                  </div>
                </div>
              </div>

              <table class="table">
                <thead class="thead-default">
                  <tr>
                    <th>URL</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody id="setting-index">
                  <%if @settings.any?%>
                    <%= render @settings%>
                  <%end%>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="card m-b-20">
            <div class="card-block">

            </div>
          </div>
        </div>
      </div>

    </div>
  </div>

<%=render "components/footer"%>

app/views/admin/settings/setting_error.js.erb
$("#setting-errors").html("<br><%= j render partial: 'layouts/flash_errors', locals: {flash: :flash}%>");

app/views/admin/settings/setting_success.js.erb
$("#setting-success").html("<br><%= j render partial: 'layouts/flash_success', locals: {flash: :flash}%>");

app/views/admin/settings/show.html.erb
<%=render "components/header"%>

  <div class="wrapper">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="page-title-box">
              <div class="btn-group pull-right">
                  <ol class="breadcrumb hide-phone p-0 m-0">
                    <li class="breadcrumb-item"><a href="#">Manage Slide</a></li>
                    <li class="breadcrumb-item active">Dashboard</li>
                  </ol>
              </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-8">
          <div class="card m-b-20">
            <div class="card-block">
              <ol>
                <hr>
                <li>Image: <%=image_tag(@setting.image, style: "width: 250px;")%></li>
              </ol>
            </div>
          </div>
        </div>
      </div>
      <%=link_to "Cancel", admin_settings_path, class: "btn btn-danger"%>
      <%=link_to "Edit", edit_admin_setting_path(@setting), class: "btn btn-success"%>
    </div>
  </div>

<%=render "components/footer"%>

app/views/admin/settings/update.js.erb
$("#setting-errors").html(" ");
$("#setting-success").html("<%= custom_flash_message%>");