config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  namespace :admin do
    root "dashboard#index"
    get "dashboard" => "dashboard#index", :as => :dashboard

    devise_scope :user do
      get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
      get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
    end

    devise_for :users, controllers: { sessions: 'admin/users/sessions'}, :passwords => 'admin/users/passwords', :skip => [:registrations]

    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
      patch 'users' => 'devise/registrations#update', :as => 'update_user_registration'
    end

    resources :products
    resources :quicks
    resources :types
    resources :brands
    resources :banners
    resources :slideshows
    resources :bigbanners
    resources :users
    resources :abouts
    resources :blogs
    resources :settings
    resources :items
    resources :categories
    resources :sparpartbrands
    resources :modes
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homes#index"
  resources :homes
  resources :products, only: [:index, :show]
  resources :brands, only: [:index, :show]
  resources :types, only: [:index, :show]
  resources :contacts, only: [:new, :create]
  resources :aboutus, only: [:index]
  resources :blogs, only: [:index, :show]
  resources :sparparts, only: [:index, :show]
  resources :items, only: [:index, :show]
  resources :sparpartbrands, only: [:index, :show]
  resources :modes, only: [:index, :show]
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :types, :through => :products, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :categories, :through => :items, dependent: :destroy
  before_save :update_slug
  def update_slug
    self.slug = brand_name.parameterize
  end

  def to_param
    slug
  end

  validates :brand_name, presence: true
  validates :brand_name , uniqueness: {case_sensitive: false}
end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController < ApplicationController
  before_action :authenticate_admin_user!
  before_action :admin_only?

  def index
    @brands = Brand.all
    @brand = Brand.new
  end

  def show
    @brand = Brand.find_by_slug(params[:id])
  end

  def new
  end

  def create
    @brand = Brand.new(brand_params)
    if @brand.save
      respond_to do |format|
        flash.now[:notice] = "Successfully Created"
        format.html{ redirect_to admin_brands_path}
        format.js
      end
    else
      respond_to do |format|
        flash.now[:error] = "Please fill the field blank or duplicate data"
        format.html{ redirect_to admin_brands_path}
        format.js{ render template: "admin/brands/brand_error.js.erb" }
      end
    end
  end

  def edit
    @brand = Brand.find_by_slug(params[:id])
  end

  def update
    @brand = Brand.find_by_slug(params[:id])
    if @brand.update(brand_params)
      redirect_to admin_brand_path(@brand), notice: "Successfully Updated"
    else
      render :edit
    end
  end


    def destroy
      @brand = Brand.destroy(params[:id])
      respond_to do |format|
        flash.now[:error] = "Delete"
        format.html { redirect_to admin_brands_url }
        format.js
      end
    end


  private

    def admin_only?
      unless current_admin_user.admin?
        unless @user == current_admin_user
          redirect_to admin_dashboard_path, notice: "Access Denied"
        end
      end
    end

    def brand_params
      params.required(:brand).permit(:brand_name)
    end
end

app/controllers/brands_controller.rb
class BrandsController < FrontEndApplicationController
  def index

  end

  def show
    @brand = Brand.find_by_slug(params[:id])
    @products = @brand.products.page params[:page]
  end
end

app/helpers/admin/brands_helper.rb
module Admin::BrandsHelper
end

app/views/brands/index.html.erb
<% title "Products | tgshobbycambodia.com"%>
<div class="wrap-main wrap-main-02">
  <%=render "components/front/header"%>
  <div class="site-content-contain">
    <div id="content" class="site-content">
        <div class="wrap container">
            <div class="row">
                <div class="col-md-9 col-md-push-3">
                    <div id="primary" class="content-area">
                        <nav class="woocommerce-breadcrumb" style="margin-top: 30px; margin-bottom: 30px;">
                            <a href="/">Home</a>
                            <%="Brands"%>
                        </nav>

                        <ul class="row products">
                            <%@products.each do |product|%>
                              <% if product.status%>
                                <li class="col-md-4 col-sm-6 col-xs-6 grid-item">
                                  <div class="product type-product has-post-thumbnail">
                                    <div class="product-image">
                                      <%=link_to product_path(product) do%>
                                      <img src="<%=product.image%>" alt="shop item">
                                      <%end%>

                                      <div class="product-action">
                                        <%=link_to product_path(product) do%>
                                        <i class="fa fa-heart-o"></i>
                                        <%end%>
                                        <%=link_to product_path(product) do%>
                                        <i class="fa fa-search-plus"></i>
                                        <%end%>
                                        <%=link_to product_path(product) do%>
                                        <i class="fa fa-list-ul"></i>
                                        <%end%>
                                      </div>
                                    </div>
                                    <h3>
                                      <%=link_to product.product_name, product_path(product)%>
                                    </h3>
                                    <div class="price">
                                      <span class="woocommerce-Price-amount amount"><%=link_to product.brand.brand_name, product.brand,class:"brand-product"%></span>
                                    </div>
                                    <div class="product-info">
                                      <div class="star-rating">
                                        <span>
                                          <strong class="rating">4</strong>
                                          out of 5,
                                        </span>
                                      </div>
                                      <%=link_to "Show Detail", product_path(product), class: "button add_to_cart_button"%>
                                    </div>
                                  </div>
                                </li>
                              <% end %>
                            <%end%>
                        </ul>

                        <%= paginate @products %>
                    </div>
                </div>
                <div class="col-md-3 col-md-pull-9">
                    <div id="secondary" class="sidebar-shop">

                        <section class="widget woocommerce widget_list_categories_product">
                            <!--widget_product_categories-->
                            <h2 class="widget-title">Products</h2>
                            <ul class="product-categories">
                              <%@types.each do |type|%>
                                <li id="<%=type.type_name.upcase.delete(' ')%>" >
                                  <a data-toggle="collapse" href="#<%=type.type_name.downcase.delete(' ')%>-<%=type.id%>" class="medusae-collapse collapsed" aria-expanded="false" aria-controls="laptop">
                                    <i class="fa fa-laptop"></i>
                                    <%=type.type_name.upcase%>
                                  </a>
                                  <ul id="<%=type.type_name.downcase.delete(' ')%>-<%=type.id%>" class="collapse" aria-expanded="false">
                                    <%type.brands.distinct.each do |brand|%>
                                      <li>
                                        <%=link_to brand_path(brand) do%>
                                          <i class="fa fa-laptop"></i>
                                          <%=brand.brand_name.upcase%>
                                        <%end%>
                                      </li>
                                    <%end%>
                                  </ul>
                                </li>
                              <%end%>
                            </ul>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>
 </div>
</div>
<%=render "components/front/footer"%>

app/views/brands/show.html.erb
<% title "Products | tgshobbycambodia.com"%>
<div class="wrap-main wrap-main-02">
  <%=render "components/front/header"%>
  <div class="site-content-contain">
    <div id="content" class="site-content">
        <div class="wrap container">
            <div class="row">
                <div class="col-md-9 col-md-push-3">
                    <div id="primary" class="content-area">
                        <nav class="woocommerce-breadcrumb" style="margin-top: 30px; margin-bottom: 30px;">
                            <a href="/">Home</a>
                            <%=link_to "Brands", brands_path%>
                            <%=@brand.brand_name%>
                        </nav>

                        <ul class="row products">
                            <%@products.each do |product|%>
                                <% if product.status%>
                                  <li class="col-md-4 col-sm-6 col-xs-6 grid-item">
                                    <div class="product type-product has-post-thumbnail">
                                      <div class="product-image">
                                        <%=link_to product_path(product) do%>
                                        <img src="<%=product.image%>" alt="shop item">
                                        <%end%>

                                        <div class="product-action">
                                          <%=link_to product_path(product) do%>
                                          <i class="fa fa-heart-o"></i>
                                          <%end%>
                                          <%=link_to product_path(product) do%>
                                          <i class="fa fa-search-plus"></i>
                                          <%end%>
                                          <%=link_to product_path(product) do%>
                                          <i class="fa fa-list-ul"></i>
                                          <%end%>
                                        </div>
                                      </div>
                                      <h3>
                                        <%=link_to product.product_name, product_path(product)%>
                                      </h3>
                                      <div class="price">
                                        <span class="woocommerce-Price-amount amount"><%=number_to_currency(product.product_price)%></span>
                                      </div>
                                      <div class="product-info">
                                        <div class="star-rating">
                                          <span>
                                            <strong class="rating">4</strong>
                                            out of 5,
                                          </span>
                                        </div>
                                        <%=link_to "Show Detail", product_path(product), class: "button add_to_cart_button"%>
                                      </div>
                                    </div>
                                  </li>
                              <%end%>
                            <%end%>
                        </ul>

                        <%= paginate @products %>
                    </div>
                </div>
                <div class="col-md-3 col-md-pull-9">
                    <div id="secondary" class="sidebar-shop">

                        <section class="widget woocommerce widget_list_categories_product">
                            <!--widget_product_categories-->
                            <h2 class="widget-title">Products</h2>
                            <ul class="product-categories">
                              <%@types.each do |type|%>
                                <li id="<%=type.type_name.upcase.delete(' ')%>" >
                                  <a data-toggle="collapse" href="#<%=type.type_name.downcase.delete(' ')%>-<%=type.id%>" class="medusae-collapse collapsed" aria-expanded="false" aria-controls="laptop">
                                    <i class="fa fa-laptop"></i>
                                    <%=type.type_name.upcase%>
                                  </a>
                                  <ul id="<%=type.type_name.downcase.delete(' ')%>-<%=type.id%>" class="collapse" aria-expanded="false">
                                    <%type.brands.distinct.each do |brand|%>
                                      <li>
                                        <%=link_to brand_path(brand) do%>
                                          <i class="fa fa-laptop"></i>
                                          <%=brand.brand_name.upcase%>
                                        <%end%>
                                      </li>
                                    <%end%>
                                  </ul>
                                </li>
                              <%end%>
                            </ul>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>
 </div>
</div>
<%=render "components/front/footer"%>